"""empty message

Revision ID: 14c8fed204c1
Revises: 50050699c4d5
Create Date: 2015-05-20 09:27:31.573311

"""

# revision identifiers, used by Alembic.
revision = '14c8fed204c1'
down_revision = '50050699c4d5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_pongs', sa.Column('ping_hash', sa.String(length=80), nullable=False))
    op.create_unique_constraint(None, 'system_pongs', ['ping_hash'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_pongs')
    op.drop_column('system_pongs', 'ping_hash')
    ### end Alembic commands ###
