"""empty message

Revision ID: 16057968da1c
Revises: 342082746925
Create Date: 2015-05-26 10:37:48.468929

"""

# revision identifiers, used by Alembic.
revision = '16057968da1c'
down_revision = '342082746925'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_updates', sa.Column('finished_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_updates', 'finished_at')
    ### end Alembic commands ###
