"""empty message

Revision ID: 1e0485123a2b
Revises: 585781195304
Create Date: 2015-04-21 14:42:11.809759

"""

# revision identifiers, used by Alembic.
revision = '1e0485123a2b'
down_revision = '585781195304'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts_installed', sa.Column('script_order', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts_installed', 'script_order')
    ### end Alembic commands ###
