"""empty message

Revision ID: 259c0691e407
Revises: 2c5bd37af2ac
Create Date: 2015-04-15 08:23:08.885062

"""

# revision identifiers, used by Alembic.
revision = '259c0691e407'
down_revision = '2c5bd37af2ac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('systems', sa.Column('cronfile', sa.String(length=80), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('systems', 'cronfile')
    ### end Alembic commands ###
