"""empty message

Revision ID: 2a91885933f2
Revises: 6500302e101
Create Date: 2014-09-05 10:51:09.891903

"""

# revision identifiers, used by Alembic.
revision = '2a91885933f2'
down_revision = '6500302e101'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'created_at')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
