"""empty message

Revision ID: 2c5bd37af2ac
Revises: 2a91885933f2
Create Date: 2014-09-05 11:38:10.324937

"""

# revision identifiers, used by Alembic.
revision = '2c5bd37af2ac'
down_revision = '2a91885933f2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_backup_logs')
    op.drop_table('system_backups')
    op.create_table('system_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_update_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_update_id', sa.Integer(), nullable=True),
    sa.Column('return_code', sa.Integer(), nullable=True),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('log_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['system_update_id'], ['system_updates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_backup_logs',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('system_backup_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('log_text', mysql.TEXT(), nullable=True),
    sa.Column('stderr', mysql.TEXT(), nullable=True),
    sa.Column('stdout', mysql.TEXT(), nullable=True),
    sa.Column('return_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['system_backup_id'], [u'system_backups.id'], name=u'system_backup_logs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('system_backups',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('system_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('is_current', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('status_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['system_id'], [u'systems.id'], name=u'system_backups_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('system_update_logs')
    op.drop_table('system_updates')
    ### end Alembic commands ###
