"""empty message

Revision ID: 3174d56b19da
Revises: 50e8720ab4cd
Create Date: 2014-09-03 09:05:34.268291

"""

# revision identifiers, used by Alembic.
revision = '3174d56b19da'
down_revision = '50e8720ab4cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_backups', sa.Column('is_current', sa.Boolean(), nullable=False))
    op.add_column('system_backups', sa.Column('status_code', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_backups', 'status_code')
    op.drop_column('system_backups', 'is_current')
    ### end Alembic commands ###
