"""empty message

Revision ID: 3267a4fd2e56
Revises: 18bcd73ac10b
Create Date: 2015-05-20 11:05:04.005444

"""

# revision identifiers, used by Alembic.
revision = '3267a4fd2e56'
down_revision = '18bcd73ac10b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts_available', sa.Column('script_exit_code_reboot', sa.BigInteger(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts_available', 'script_exit_code_reboot')
    ### end Alembic commands ###
