"""empty message

Revision ID: 342082746925
Revises: 3267a4fd2e56
Create Date: 2015-05-22 14:03:38.144015

"""

# revision identifiers, used by Alembic.
revision = '342082746925'
down_revision = '3267a4fd2e56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_updates', sa.Column('group_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_updates', 'group_id')
    ### end Alembic commands ###
