"""empty message

Revision ID: 39614022c57
Revises: 259c0691e407
Create Date: 2015-04-21 10:28:09.070301

"""

# revision identifiers, used by Alembic.
revision = '39614022c57'
down_revision = '259c0691e407'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts_available',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripts_available')
    ### end Alembic commands ###
