"""empty message

Revision ID: 3e24919ec2eb
Revises: add4c1812ca
Create Date: 2015-05-18 10:20:57.712543

"""

# revision identifiers, used by Alembic.
revision = '3e24919ec2eb'
down_revision = 'add4c1812ca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('system_id', table_name='scripts_installed')
    ### end Alembic commands ###


def downgrade():
    pass
