"""empty message

Revision ID: 436c4fb517cd
Revises: 16057968da1c
Create Date: 2015-06-05 08:31:52.772114

"""

# revision identifiers, used by Alembic.
revision = '436c4fb517cd'
down_revision = '16057968da1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('update_groups', sa.Column('id', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_groups', 'id')
    ### end Alembic commands ###
