"""empty message

Revision ID: 50e8720ab4cd
Revises: 4b189495dccd
Create Date: 2014-09-03 08:41:59.675678

"""

# revision identifiers, used by Alembic.
revision = '50e8720ab4cd'
down_revision = '4b189495dccd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_backup_logs', sa.Column('return_code', sa.Integer(), nullable=True))
    op.add_column('system_backups', sa.Column('backup_id', sa.Integer(), nullable=False))
    op.drop_column('system_backups', 'return_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_backups', sa.Column('return_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('system_backups', 'backup_id')
    op.drop_column('system_backup_logs', 'return_code')
    ### end Alembic commands ###
