"""empty message

Revision ID: 585781195304
Revises: 39614022c57
Create Date: 2015-04-21 14:41:03.866763

"""

# revision identifiers, used by Alembic.
revision = '585781195304'
down_revision = '39614022c57'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scripts_installed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('script_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['script_id'], ['scripts_available.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scripts_installed')
    ### end Alembic commands ###
