"""empty message

Revision ID: 6500302e101
Revises: 3174d56b19da
Create Date: 2014-09-04 07:43:16.908423

"""

# revision identifiers, used by Alembic.
revision = '6500302e101'
down_revision = '3174d56b19da'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_backups', 'backup_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_backups', sa.Column('backup_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    ### end Alembic commands ###
