"""empty message

Revision ID: 65b26fe497b
Revises: 28ded70f2f95
Create Date: 2015-05-13 11:13:09.994579

"""

# revision identifiers, used by Alembic.
revision = '65b26fe497b'
down_revision = '28ded70f2f95'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('update_groups',
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('update_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['system_id'], ['systems.id'], ),
    sa.ForeignKeyConstraint(['update_group_id'], ['update_group.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_groups')
    op.drop_table('update_group')
    ### end Alembic commands ###
