"""empty message

Revision ID: add4c1812ca
Revises: 65b26fe497b
Create Date: 2015-05-18 10:07:24.852895

"""

# revision identifiers, used by Alembic.
revision = 'add4c1812ca'
down_revision = '65b26fe497b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('scripts_installed', sa.Column('group_id', sa.Integer(), nullable=True))
    #op.drop_column('scripts_installed', 'system_id')
    ### end Alembic commands ###
    pass


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts_installed', sa.Column('system_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('scripts_installed', 'group_id')
    ### end Alembic commands ###
